# Generated by Django 5.2 on 2025-06-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='document',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
