# Generated by Django 5.2 on 2025-06-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almaweb', '0002_news_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='document',
        ),
    ]
