# Generated by Django 5.2 on 2025-06-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaweb', '0003_remove_news_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
