# Generated by Django 5.2 on 2025-05-09 15:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paynow_reference', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('fees', 'FEES PAYMENT'), ('tuition', 'TUITION PAYMENT'), ('donation', 'DONATIONS'), ('other', 'OTHER')], max_length=20)),
                ('status', models.CharField(choices=[('fees', 'FEES PAYMENT'), ('tuition', 'TUITION PAYMENT'), ('donation', 'DONATIONS'), ('other', 'OTHER')], default='pending', max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('application_type', models.CharField(choices=[('masters', 'Masters'), ('certificate', 'Certificate')], default='masters', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default=datetime.date(2001, 12, 12))),
                ('gender', models.CharField(max_length=10)),
                ('national_id', models.CharField(max_length=25)),
                ('title', models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.')], max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('citizenship', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('disability', models.BooleanField(default=False)),
                ('disability_details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paynow_reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_type', models.CharField(choices=[('application_fee', 'APPLICATION FEE PAYMENT')], max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='authentication.application')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_level_certificate', models.FileField(upload_to='documents/a_level_certificate')),
                ('o_level_certificate', models.FileField(upload_to='documents/o_level_certificate')),
                ('CV', models.FileField(upload_to='documents/CV')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='authentication.application')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateEducational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_of_study', models.CharField(max_length=100)),
                ('institution_attended', models.CharField(max_length=110)),
                ('level_of_study', models.CharField(max_length=100)),
                ('major_subjects', models.CharField(max_length=100)),
                ('date_awarded', models.DateField(default=datetime.date(2001, 12, 12))),
                ('programme_applied_for', models.CharField(choices=[('CLM', 'Certificate In Leadership & Management (CLM)'), ('CADM', 'Certificate in Agribusiness Development and Management (CADM)')], max_length=100)),
                ('preferred_learning_format', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], max_length=10)),
                ('prospective_sponsors', models.CharField(max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_edu', to='authentication.application')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('permanent_address_no_street', models.CharField(max_length=255)),
                ('permanent_address_apt_unit', models.CharField(max_length=255)),
                ('permanent_address_state_province', models.CharField(max_length=100)),
                ('home_phone', models.CharField(max_length=15)),
                ('office_phone', models.CharField(max_length=15)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='authentication.application')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_certificate', models.FileField(upload_to='documents/birth_certificates/')),
                ('id_document', models.FileField(upload_to='documents/id_documents/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='authentication.application')),
            ],
        ),
        migrations.CreateModel(
            name='MastersDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.FileField(upload_to='documents/transcript')),
                ('degree_certificate', models.FileField(upload_to='documents/degree_certificate')),
                ('a_level_certificate', models.FileField(upload_to='documents/a_level_certificate')),
                ('o_level_certificate', models.FileField(upload_to='documents/o_level_certificate')),
                ('CV', models.FileField(upload_to='documents/CV')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='authentication.application')),
            ],
        ),
        migrations.CreateModel(
            name='MastersEducational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_of_study', models.CharField(max_length=100)),
                ('awarding_institution', models.CharField(max_length=100)),
                ('degree_diploma_level_classification', models.CharField(max_length=100)),
                ('major_subjects', models.CharField(max_length=255)),
                ('date_awarded', models.DateField(default=datetime.date(2001, 12, 12))),
                ('preferred_learning_format', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], max_length=10)),
                ('programme_applied_for', models.CharField(choices=[('MBA', 'MBA (Leadership & Management) (MBALM)'), ('MSc', 'MSc. (Governance & Leadership) (MGOVL)')], max_length=100)),
                ('prospective_sponsors', models.CharField(max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational', to='authentication.application')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_did_you_hear_about_ALMA', models.CharField(max_length=255)),
                ('additional_remarks', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other', to='authentication.application')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=25, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='authentication.application')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=100)),
                ('work_details', models.TextField()),
                ('work_experience_from', models.DateField(default=datetime.date(2000, 12, 12))),
                ('work_experience_to', models.DateField(default=datetime.date(2001, 12, 12))),
                ('reference_1_name', models.CharField(max_length=100)),
                ('reference_1_email', models.EmailField(max_length=50)),
                ('reference_1_phone_number', models.CharField(max_length=15)),
                ('reference_2_name', models.CharField(max_length=100)),
                ('reference_2_email', models.EmailField(max_length=50)),
                ('reference_2_phone_number', models.CharField(max_length=15)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='authentication.application')),
            ],
        ),
    ]
