# Generated by Django 5.2 on 2025-05-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpayments',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalpayments',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
