# Generated by Django 5.2 on 2025-06-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_applicationpayments_redirect_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='acca_images/')),
            ],
        ),
    ]
