# Generated by Django 5.2 on 2025-06-04 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_acca'),
    ]

    operations = [
        migrations.AddField(
            model_name='acca',
            name='application',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='accas', to='authentication.application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acca',
            name='focus_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acca',
            name='level',
            field=models.CharField(choices=[('FUNDAMENTAL', 'Fundamental Level'), ('APPLIED_SKILLS', 'Applied Skills'), ('STRATEGIC_PROFESSIONAL', 'Strategic Professional')], default='FUNDAMENTAL', max_length=60),
        ),
    ]
