# Generated by Django 5.2 on 2025-06-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_acca_application_acca_focus_area_acca_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='acca',
            name='focus_area',
        ),
        migrations.AddField(
            model_name='acca',
            name='focus_areas',
            field=models.ManyToManyField(blank=True, to='authentication.focusarea'),
        ),
    ]
