# Generated by Django 5.2 on 2025-06-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_focusarea_remove_acca_focus_area_acca_focus_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acca',
            name='focus_areas',
        ),
        migrations.RemoveField(
            model_name='acca',
            name='image',
        ),
        migrations.AddField(
            model_name='acca',
            name='focus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acca',
            name='level_selection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acca',
            name='module_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acca',
            name='level',
            field=models.CharField(choices=[('FUNDAMENTAL', 'Applied Knowledge'), ('APPLIED_SKILLS', 'Applied Skills'), ('STRATEGIC_PROFESSIONAL', 'Strategic Professional')], default='FUNDAMENTAL', max_length=60),
        ),
        migrations.DeleteModel(
            name='FocusArea',
        ),
    ]
