# Generated by Django 5.2 on 2025-06-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_acca_focus_areas_remove_acca_image_acca_focus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterseducational',
            name='period_of_study',
        ),
        migrations.DeleteModel(
            name='Acca',
        ),
    ]
